//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrescriptionsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string docID { get; set; }
        public string docFirstName { get; set; }
        public string docLastName { get; set; }
        public string docCountry { get; set; }
        public string password { get; set; }
    }
}
