//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrescriptionsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public string docID { get; set; }
        public string patientID { get; set; }
        public string pillName { get; set; }
        public System.DateTime timeAdded { get; set; }
        public string info { get; set; }
        public int recordID { get; set; }
    }
}
